### ISSUE TITLE
Local fonts not loaded on percy rendering environment

### ISSUE THREAD

**Issue by frixatrix** [percy/percy-puppeteer#189]
Hi,

Faced an issue with local fonts failing to be rendered on percy rendering environment.
It works fine locally, it was verified by additional listener for this font loading.

Example of expected appearance:
<img width="316" alt="expected" src="https://user-images.githubusercontent.com/25078398/89630644-f466d100-d89f-11ea-8e9c-e58edffbd59c.png">

Example of received screenshot from percy:
<img width="419" alt="received" src="https://user-images.githubusercontent.com/25078398/89630668-fdf03900-d89f-11ea-98ac-bee1ddd77c72.png">

Tried:
- increasing timeouts
- adding allowed-hosts from https://docs.percy.io/docs/font-services

Issue is tricky for me and is not reproducible for 100%.

Please advise how to fix or workaround it on my side, or will it be fixed on percy side(if so, when?).

Thank you in advance.

Unfortunately, spent around 15% of monthly screenshots trying to fix this issue until realised it cannot be fixed on my side.

**Comment by Robdel12** [comment]
Hey @frixatrix would you be able to share a Percy build link where this is happening?

**Comment by frixatrix** [comment]
> Hey @frixatrix would you be able to share a Percy build link where this is happening?

Hey @Robdel12 could you please share your e-mail for this?
Thank you in advance.

**Comment by Robdel12** [comment]
No problem! You can send the build link over to `support@percy.io`

**Comment by frixatrix** [comment]
Hi @Robdel12 thank you. Sent email with details.

**Comment by Robdel12** [comment]
Thanks for sending that over! This one is interesting -- it looks like the SDK isn't capturing the font in the default asset discovery timeout window. By default our SDKs will wait 125ms for zero network requests to be made by the DOM snapshot we've captured. Sometimes assets aren't requested in that timeout (I think that's what's going on here). You can increase this timeout by either passing a CLI flag (`percy exec -t 250 -- [test command]`) or by creating a Percy config file. For example, as a `.percy.yml` file:

```yml
version: 1
agent:
  asset-discovery:
    network-idle-timeout: 250 # ms
```

This _should_ clear this up. It's safe to take that timeout up to ~500ms (anything higher means there's probably something else going on).

**Comment by frixatrix** [comment]
Hi @Robdel12 thank you for investigating and possible solution.
Will try it out, but as it's not a persistent issue I will be able to confirm it in some time in future (as not going to spend another 15% of screenshots for this 😄 )
