### ISSUE TITLE
PNG images are not displayed

### ISSUE THREAD

**Issue by pashax0** [percy/percy-puppeteer#248]
PNG images are not loaded in screenshot results (on this page SVG - displayed, JPG - random (sometime show), PNG - only alt text): https://percy.io/10ecbde0/Lition/builds/8869567/changed/503202803?browser=firefox&browser_ids=9%2C14&subcategories=approved&viewLayout=side-by-side&viewMode=new&width=1920&widths=375%2C1920
On puppeteer screenshot displayed all images.

This happened in period from 2021-02-08 - 2021-02-15, before - everything works fine

**Comment by wwilsman** [comment]
Hey @pashax0! This doesn't appear to be an issue with this SDK in particular. Rather, it looks like it could be an asset discovery or rendering issue instead. You can [open a support ticket](https://www.browserstack.com/contact?ref=percy#technical-support) and somebody will be happy to help determine what's causing this for you.
