### ISSUE TITLE
`ReferenceError: window is not defined` with Jest 28 and jest-puppeteer

### ISSUE THREAD

**Issue by igorpupkinable** [percy/percy-puppeteer#451]
## The problem

`ReferenceError: window is not defined` is thrown after upgrading to Jest 28.
**Same setup works fine with Jest 27 though.**

## Environment

- Node version: 16.15
- `@percy/cli` version: 1.6.0
- OS version: Ubuntu 20 LTS
- Type of shell command-line [interface]: bash
```
"dependencies": {
    "@percy/cli": "^1.6.0",
    "@percy/puppeteer": "^2.0.2",
    "expect-puppeteer": "^6.1.1",
    "jest": "^28.1.2",
    "jest-puppeteer": "^6.1.1",
    "puppeteer": "^15.3.2"
},
```

## Details

`ReferenceError: window is not defined` error occurs when referencing `percySnapshot` method after upgrading to Jest 28.
Installing JSDOM environment explicitly does not help either. https://jestjs.io/docs/upgrading-to-jest28#jsdom

## Debug logs
```
Test suite failed to run

    The error below may be caused by using the wrong test environment, see https://jestjs.io/docs/configuration#testenvironment-string.
    Consider using the "jsdom" test environment.
    
    ReferenceError: window is not defined

      at Object.<anonymous> (node_modules/@percy/sdk-utils/dist/bundle.js:347:9)
      at Object.<anonymous> (node_modules/@percy/puppeteer/index.js:1:35)

```

## Code to reproduce issue
Install Jest 28 and configure latest `jest-puppeteer` as per documentation https://jestjs.io/docs/28.0/puppeteer#use-jest-puppeteer-preset
Run simple test:
```
import percySnapshot from '@percy/puppeteer';

describe('E2E test', () => {
  it('renders', async () => {
    await page.goto(`https://github.com`);

    await percySnapshot(page, 'homepage');
  });
});

```

**Comment by igorpupkinable** [comment]
https://github.com/smooth-code/jest-puppeteer/issues/295

**Comment by wwilsman** [comment]
Hey @igorpupkinable!

It looks like the error stack your provided is referencing the browser bundle of `@percy/sdk-utils`

> node_modules/@percy/sdk-utils/dist/bundle.js

This should only be used in browser environments (where `window` would be available). For node, it should be using the main/node exports defined by the package.json: https://github.com/percy/cli/blob/master/packages/sdk-utils/package.json#L22-L28

Since you say this is only an issue when upgrading jest, it sounds like they might have changed their bespoke module loader which is not honoring native node module loading.

**Comment by frixatrix** [comment]
@wwilsman hi, have the same issue with stack:

`"engines": {
    "node": ">=16.16 <17",
    "npm": ">=8.13.2"
  },
  "dependencies": {
    "puppeteer": "^14.0.0"
  },
  "devDependencies": {
    "@percy/cli": "^1.1.3",
    "@percy/puppeteer": "^2.0.2",
    "eslint": "^8.15.0",
    "jest": "^28.1.0",
    "jest-circus": "^28.1.0",
    "jest-puppeteer": "^6.1.0",
    "puppeteer-core": "^14.0.0"
 }`
 
 and it was working fine for last few months until few days ago. 
There were no changes from my side to the setup or tests.

Trying to find a way how to just return state back to normal and get running tests as before.

**Comment by Robdel12** [comment]
Hey @frixatrix! It sounds like Jest is broken in how they're importing modules. In a later version we updated how the export works to match the spec(s): https://github.com/percy/cli/pull/962
