### ISSUE TITLE
Improve error message when large DOM is sent

### ISSUE THREAD

**Issue by djones** [percy/percy-puppeteer#70]
When a DOM is between 10mb and 15mb an unclear error message appears. Add better handling around this case by outputting a clear error message.

**Comment by Robdel12** [comment]
I think we might already have logging for this, but `LOG_LEVEL=debug` needs to be enabled: https://github.com/percy/percy-agent/blob/6375078eb74a263d6a6e2e131225e9206f2f1ae7/src/utils/sdk-utils.ts#L25

Might also have to be done upstream from here. I'm going to try and slice some time out today to confirm

**Comment by Robdel12** [comment]
Can confirm adding `maxContentLength` to our `postSnapshot` method makes it work 👍 

```
 ✗ yarn percy
yarn run v1.15.2
$ percy exec -- node ./index.js
[percy] created build #610: [URL]
[percy] percy has started.
[percy] snapshot taken: 'Does this snapshot?'
[percy] stopping percy...
[percy] waiting for 1 snapshots to complete...
[percy] done.
[percy] finalized build #610: [URL]
✨  Done in 25.79s.
```

**Comment by djones** [comment]
Thanks @Robdel12. Pulling a PR for this together shortly.

**Comment by djones** [comment]
Closing with the release of https://github.com/percy/percy-agent/pull/118

Upgrade to `@percy/puppeteer@1.0.6` or higher to be able to snapshot larger ~16mb DOMs.
